name: Test Renovate PRs

on:
    pull_request:
        types: [opened, synchronize, reopened]
        paths:
            - "package.json"
            - "package-lock.json"

jobs:
    test:
        name: Test Renovate Updates
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run linting
              run: npm run lint

            - name: Build project
              run: npm run build

            - name: Run tests (if available)
              run: |
                  if npm run test --dry-run 2>/dev/null; then
                    npm run test
                  else
                    echo "No test script found, skipping tests"
                  fi

            - name: Check for vulnerabilities
              run: |
                  echo "## 🔍 Security Check" >> $GITHUB_STEP_SUMMARY
                  npm audit --audit-level=moderate || true

                  VULN_COUNT=$(npm audit --audit-level=moderate --json 2>/dev/null | jq '.metadata.vulnerabilities.total // 0')
                  echo "Vulnerabilities found: $VULN_COUNT" >> $GITHUB_STEP_SUMMARY

                  if [ "$VULN_COUNT" -gt 0 ]; then
                    echo "⚠️ **$VULN_COUNT vulnerabilities detected**" >> $GITHUB_STEP_SUMMARY
                    echo "Consider running \`npm audit fix\` if safe to do so" >> $GITHUB_STEP_SUMMARY
                  else
                    echo "✅ No vulnerabilities found" >> $GITHUB_STEP_SUMMARY
                  fi

            - name: Comment on PR
              if: github.event_name == 'pull_request'
              uses: actions/github-script@v7
              with:
                  script: |
                      const { data: pr } = await github.rest.pulls.get({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: context.issue.number
                      });

                      const isRenovatePR = pr.labels.some(label => label.name === 'renovate');

                      if (isRenovatePR) {
                        const comment = `## 🤖 Renovate PR Test Results
                        
                        **Build Status:** ✅ Successful
                        **Linting:** ✅ Passed
                        **Security Check:** Completed
                        
                        This PR has been automatically tested and is ready for review.
                        
                        **Next Steps:**
                        1. Review the dependency changes
                        2. Test the application locally if needed
                        3. Merge if everything looks good
                        
                        ---
                        *This comment was automatically generated by the Renovate test workflow*`;
                        
                        await github.rest.issues.createComment({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: context.issue.number,
                          body: comment
                        });
                      }
